apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-api-config
  namespace: default
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:80"
  RabbitMQ__Host: "rabbitmq-service"
  RabbitMQ__Username: "guest"
  RabbitMQ__Password: "guest"
  SWAGGER_BASE_PATH: "/payments"
  NEW_RELIC_APP_NAME: "fcg-payments-api"
